from __future__ import annotations

from typing import Any, Dict


STRINGS: Dict[str, Dict[str, str]] = {
    "ru": {
        "menu.title": "КТО ХОЧЕТ СТАТЬ МИЛЛИОНЕРОМ?",
        "menu.play": "ИГРАТЬ",
        "menu.profile": "ПРОФИЛЬ",
        "menu.settings": "НАСТРОЙКИ",
        "menu.exit": "ВЫХОД",
        "menu.main_menu": "В главное меню",
        "common.back": "Назад",

        "settings.title": "НАСТРОЙКИ",
        "settings.sound": "Звук",
        "settings.volume": "Громкость",
        "settings.music": "Музыка",
        "settings.options": "Опции",
        "settings.timer_in_game": "Таймер в игре",
        "settings.back": "Назад",
        "settings.language": "Язык",
        "settings.language_ru": "Русский",
        "settings.language_ky": "Кыргызча",
        "settings.language_en": "English",

        "profile.back": "← НАЗАД",
        "profile.title": "ПРОФИЛЬ ИГРОКА",
        "profile.player_label": "ИГРОК",
        "profile.rank_label": "ТЕКУЩИЙ РАНГ: {rank}",
        "profile.stats_title": "СТАТИСТИКА ИГРОКА",
        "profile.accuracy": "ТОЧНОСТЬ ОТВЕТОВ: {acc:.1f}%",
        "profile.records_tab": "РЕКОРДЫ",
        "profile.achievements_tab": "ДОСТИЖЕНИЯ",
        "profile.records_header": "РЕКОРДЫ",
        "profile.records_empty": "Рекордов пока нет",
        "records_table.rank": "№",
        "records_table.name": "Имя",
        "records_table.series": "Серия",
        "records_table.time": "Время",
        "records_table.winnings": "Выигрыш",

        "in_game.question_header": "ВОПРОС №{n}",
        "in_game.timer": "ОСТАЛОСЬ ВРЕМЕНИ: {t} c.",
        "lifeline.5050": "50:50",
        "lifeline.call_friend": "ЗВОНОК\nДРУГУ",
        "lifeline.audience": "ПОМОЩЬ\nЗАЛА",
        "lifeline.take_money": "ЗАБРАТЬ\nДЕНЬГИ",
        "lifeline.second_chance": "ПРАВО\nНА ОШИБКУ",

        "gameover.win_millionaire": "ПОЗДРАВЛЯЕМ!\nВЫ МИЛЛИОНЕР!",
        "gameover.take_money": "ВЫ ЗАБРАЛИ ДЕНЬГИ!",
        "gameover.end": "ИГРА ОКОНЧЕНА",
        "gameover.restart": "Играть снова",
        "gameover.return_to_menu": "Вернуться в меню",

        "dialogs.right_to_mistake.title": "Право на ошибку",
        "dialogs.right_to_mistake.body": "У вас было право на ошибку! Попробуйте еще раз.",
        "dialogs.ok": "OK",

        "dialogs.export.success": "Файл сохранен в exports/",
        "dialogs.export.error_title": "Экспорт",
        "dialogs.export.error_ok": "OK",

        # Achievements RU
        "achievement.category.wealth": "Путь к богатству",
        "achievement.category.hints": "Работа с подсказками",
        "achievement.category.difficult": "Сложные ситуации",
        "achievement.category.special": "Особые заслуги",

        "achievement.first_step.title": "Первый шаг",
        "achievement.first_step.desc": "Дать первый правильный ответ",
        "achievement.first_million.title": "Первый миллион",
        "achievement.first_million.desc": "Впервые выиграть 1,000,000 за одну игру",
        "achievement.cold_blood.title": "Хладнокровие",
        "achievement.cold_blood.desc": "Ответить на 10 вопросов, тратя менее 10 секунд на каждый",
        "achievement.jackpot.title": "Джекпот!",
        "achievement.jackpot.desc": "Ответить на финальный, 15-й вопрос",
        "achievement.veteran.title": "Ветеран",
        "achievement.veteran.desc": "Ответить на 500 вопросов за всё время",
        "achievement.risky_guy.title": "Рисковый парень",
        "achievement.risky_guy.desc": "Дойти до 10-го вопроса, не потратив ни одной подсказки",
        "achievement.voice_of_people.title": "Глас народа",
        "achievement.voice_of_people.desc": "Победить, выбрав вариант «Помощь зала»",
        "achievement.friend_in_need.title": "Друг в беде",
        "achievement.friend_in_need.desc": "Использовать «Звонок другу» на вопросе выше 10-го и ответить верно",
        "achievement.va_bank.title": "Ва-банк",
        "achievement.va_bank.desc": "Использовать все три подсказки на одном и том же вопросе",
        "achievement.own_mind.title": "Своим умом",
        "achievement.own_mind.desc": "Пройти всю игру до конца, не использовав ни одной подсказки",
        "achievement.on_the_edge.title": "На грани",
        "achievement.on_the_edge.desc": "Дать верный ответ, когда на таймере осталось меньше 2 секунд",
        "achievement.bird_in_hand.title": "Синица в руках",
        "achievement.bird_in_hand.desc": "Забрать деньги (кнопка «Take Money») на вопросе выше 12-го",
        "achievement.bitter_experience.title": "Горький опыт",
        "achievement.bitter_experience.desc": "Проиграть на финальном 15-м вопросе",
        "achievement.sprinter.title": "Спринтер",
        "achievement.sprinter.desc": "Пройти всю игру (все 15 вопросов) быстрее чем за 2 минуты",
        "achievement.intellectual_series.title": "Интеллектуальная серия",
        "achievement.intellectual_series.desc": "Три игры подряд без единой ошибки",
        "achievement.magnate.title": "Магнат",
        "achievement.magnate.desc": "Накопить общий капитал в 1 000 000 000",
        "achievement.cautious_strategist.title": "Осторожный стратег",
        "achievement.cautious_strategist.desc": "Забрать деньги 20 раз за всю карьеру",
        "achievement.history_expert.title": "Знаток истории",
        "achievement.history_expert.desc": "Дать 50 правильных ответов в категории «История»",
        "achievement.jack_of_all_trades.title": "Мастер на все руки",
        "achievement.jack_of_all_trades.desc": "Правильно ответить на вопросы из 10 разных областей знаний",
        "achievement.club_legend.title": "Легенда клуба",
        "achievement.club_legend.desc": "Собрать остальные 19 достижений",
    },
    "ky": {
        "menu.title": "КИМ МИЛЛИОНЕР БОЛГУСУ КЕЛЕТ?",
        "menu.play": "ОЙНОО",
        "menu.profile": "ПРОФИЛЬ",
        "menu.settings": "ЖӨНДӨӨ",
        "menu.exit": "ЧЫГУУ",
        "menu.main_menu": "Башкы меню",
        "common.back": "Артка",

        "settings.title": "ЖӨНДӨӨ",
        "settings.sound": "Үн",
        "settings.volume": "Дыбыс",
        "settings.music": "Күүлөр",
        "settings.options": "Орнотуулар",
        "settings.timer_in_game": "Оюндагы таймер",
        "settings.back": "Артка",
        "settings.language": "Тил",
        "settings.language_ru": "Орусча",
        "settings.language_ky": "Кыргызча",
        "settings.language_en": "English",

        "profile.back": "← АРТКА",
        "profile.title": "ОЮНЧУНУН ПРОФИЛИ",
        "profile.player_label": "ОЮНЧУ",
        "profile.rank_label": "АЗЫРКЫ ДАРАЖА: {rank}",
        "profile.stats_title": "ОЮНЧУНУН СТАТИСТИКАСЫ",
        "profile.accuracy": "ЖООПТУН ТАКТЫГЫ: {acc:.1f}%",
        "profile.records_tab": "РЕКОРДДОР",
        "profile.achievements_tab": "ЖЕТИШКЕНДИКТЕР",
        "profile.records_header": "РЕКОРДДОР",
        "profile.records_empty": "Азырынча рекорд жок",
        "records_table.rank": "№",
        "records_table.name": "Аты",
        "records_table.series": "Серия",
        "records_table.time": "Убакыт",
        "records_table.winnings": "Утуш суммасы",

        "in_game.question_header": "СУРОО №{n}",
        "in_game.timer": "КАЛГАН УБАКЫТ: {t} c.",
        "lifeline.5050": "50:50",
        "lifeline.call_friend": "ДОСУҢА\nЧАЛУУ",
        "lifeline.audience": "ЗАЛДЫН\nСТАТИСТИКАСЫ",
        "lifeline.take_money": "АКЧАНЫ\nАЛУУ",
        "lifeline.second_chance": "КАТА ҮЧҮН\nУКУК",

        "gameover.win_millionaire": "КУТТЫКТАЙМ! СЕН МИЛЛИОНЕРСИҢ!",
        "gameover.take_money": "СЕН АКЧАНЫ АЛДЫҢ!",
        "gameover.end": "ОЮН АЯКТАЛДЫ",
        "gameover.restart": "Кайра ойноо",
        "gameover.return_to_menu": "Менюга кайтуу",

        "dialogs.right_to_mistake.title": "Ката үчүн укук",
        "dialogs.right_to_mistake.body": "Сага ката кетирүүгө уруксат берилди! Дагы бир жолу аракет кыл.",
        "dialogs.ok": "OK",

        "dialogs.export.success": "Файл exports/ папкасына сакталды",
        "dialogs.export.error_title": "Экспорт",
        "dialogs.export.error_ok": "OK",

        # Achievements KY
        "achievement.category.wealth": "Байлыкка жол",
        "achievement.category.hints": "Жардамдар менен иштөө",
        "achievement.category.difficult": "Татаал кырдаалдар",
        "achievement.category.special": "Өзгөчө эмгектер",

        "achievement.first_step.title": "Биринчи кадам",
        "achievement.first_step.desc": "Биринчи туура жооп берүү",
        "achievement.first_million.title": "Биринчи миллион",
        "achievement.first_million.desc": "Биринчи жолу бир оюнда 1,000,000 утуп алуу",
        "achievement.cold_blood.title": "Суук кандуулук",
        "achievement.cold_blood.desc": "Ар бирине 10 секунддан аз убакыт коротуп, 10 суроого жооп берүү",
        "achievement.jackpot.title": "Джекпот!",
        "achievement.jackpot.desc": "Акыркы 15-суроого жооп берүү",
        "achievement.veteran.title": "Ветеран",
        "achievement.veteran.desc": "Жалпысынан 500 суроого жооп берүү",
        "achievement.risky_guy.title": "Тобокелчи",
        "achievement.risky_guy.desc": "Бир дагы жардам колдонбостон 10-суроого чейин жетүү",
        "achievement.voice_of_people.title": "Элдин үнү",
        "achievement.voice_of_people.desc": "«Залдын жардамы» аркылуу жеңишке жетүү",
        "achievement.friend_in_need.title": "Кыйынчылыктагы дос",
        "achievement.friend_in_need.desc": "10-суроодон жогору «Досуңа чалууну» колдонуп, туура жооп берүү",
        "achievement.va_bank.title": "Ва-банк",
        "achievement.va_bank.desc": "Бир эле суроодо үч жардамдын тең колдонуу",
        "achievement.own_mind.title": "Өз акылы менен",
        "achievement.own_mind.desc": "Бир дагы жардам колдонбостон оюнду аягына чейин бүтүрүү",
        "achievement.on_the_edge.title": "Четте",
        "achievement.on_the_edge.desc": "Таймерде 2 секунддан аз калганда туура жооп берүү",
        "achievement.bird_in_hand.title": "Колдогу чымчык",
        "achievement.bird_in_hand.desc": "12-суроодон жогору акчаны алып кетүү",
        "achievement.bitter_experience.title": "Ачуу тажрыйба",
        "achievement.bitter_experience.desc": "Акыркы 15-суроодо утулуп калуу",
        "achievement.sprinter.title": "Спринтер",
        "achievement.sprinter.desc": "Оюнду (бардык 15 суроону) 2 мүнөттөн тезирээк бүтүрүү",
        "achievement.intellectual_series.title": "Интеллектуалдык серия",
        "achievement.intellectual_series.desc": "Катарынан үч оюнду катасыз ойноо",
        "achievement.magnate.title": "Магнат",
        "achievement.magnate.desc": "Жалпы 1,000,000,000 капитал топтоо",
        "achievement.cautious_strategist.title": "Сак стратег",
        "achievement.cautious_strategist.desc": "Карьераңызда 20 жолу акчаны алып кетүү",
        "achievement.history_expert.title": "Тарых билгичи",
        "achievement.history_expert.desc": "«Тарых» категориясында 50 туура жооп берүү",
        "achievement.jack_of_all_trades.title": "Ар тараптуу мастер",
        "achievement.jack_of_all_trades.desc": "10 башка илим чөйрөсүндөгү суроолорго туура жооп берүү",
        "achievement.club_legend.title": "Клуб легендасы",
        "achievement.club_legend.desc": "Калган 19 жетишкендиктин баарын чогултуу",
    },
    "en": {
        "menu.title": "WHO WANTS TO BE A MILLIONAIRE?",
        "menu.play": "PLAY",
        "menu.profile": "PROFILE",
        "menu.settings": "SETTINGS",
        "menu.exit": "EXIT",
        "menu.main_menu": "Main menu",
        "common.back": "Back",

        "settings.title": "SETTINGS",
        "settings.sound": "Sound",
        "settings.volume": "Volume",
        "settings.music": "Music",
        "settings.options": "Options",
        "settings.timer_in_game": "In-game timer",
        "settings.back": "Back",
        "settings.language": "Language",
        "settings.language_ru": "Russian",
        "settings.language_ky": "Kyrgyz",
        "settings.language_en": "English",

        "profile.back": "← BACK",
        "profile.title": "PLAYER PROFILE",
        "profile.player_label": "PLAYER",
        "profile.rank_label": "CURRENT RANK: {rank}",
        "profile.stats_title": "PLAYER STATS",
        "profile.accuracy": "ACCURACY: {acc:.1f}%",
        "profile.records_tab": "RECORDS",
        "profile.achievements_tab": "ACHIEVEMENTS",
        "profile.records_header": "RECORDS",
        "profile.records_empty": "No records yet",
        "records_table.rank": "№",
        "records_table.name": "Name",
        "records_table.series": "Series",
        "records_table.time": "Time",
        "records_table.winnings": "Winnings",

        "in_game.question_header": "QUESTION №{n}",
        "in_game.timer": "TIME LEFT: {t} s.",
        "lifeline.5050": "50:50",
        "lifeline.call_friend": "CALL\nA FRIEND",
        "lifeline.audience": "AUDIENCE\nHELP",
        "lifeline.take_money": "TAKE\nTHE MONEY",
        "lifeline.second_chance": "SECOND\nCHANCE",

        "gameover.win_millionaire": "CONGRATULATIONS!\nYOU ARE A MILLIONAIRE!",
        "gameover.take_money": "YOU TOOK THE MONEY!",
        "gameover.end": "GAME OVER",
        "gameover.restart": "Play again",
        "gameover.return_to_menu": "Return to Menu",

        "dialogs.right_to_mistake.title": "Right to mistake",
        "dialogs.right_to_mistake.body": "You had a right to make a mistake! Try again.",
        "dialogs.ok": "OK",

        "dialogs.export.success": "File saved to exports/",
        "dialogs.export.error_title": "Export",
        "dialogs.export.error_ok": "OK",

        # Achievements EN
        "achievement.category.wealth": "Path to Wealth",
        "achievement.category.hints": "Lifeline Mastery",
        "achievement.category.difficult": "Tough Situations",
        "achievement.category.special": "Special Merits",

        "achievement.first_step.title": "First Step",
        "achievement.first_step.desc": "Give your first correct answer",
        "achievement.first_million.title": "First Million",
        "achievement.first_million.desc": "Win 1,000,000 in a single game for the first time",
        "achievement.cold_blood.title": "Cold-Blooded",
        "achievement.cold_blood.desc": "Answer 10 questions spending less than 10 seconds on each",
        "achievement.jackpot.title": "Jackpot!",
        "achievement.jackpot.desc": "Answer the final 15th question",
        "achievement.veteran.title": "Veteran",
        "achievement.veteran.desc": "Answer 500 questions in total",
        "achievement.risky_guy.title": "Risk Taker",
        "achievement.risky_guy.desc": "Reach the 10th question without using any lifelines",
        "achievement.voice_of_people.title": "Voice of the People",
        "achievement.voice_of_people.desc": "Win by choosing the 'Ask the Audience' option",
        "achievement.friend_in_need.title": "Friend in Need",
        "achievement.friend_in_need.desc": "Use 'Phone a Friend' on question 10+ and answer correctly",
        "achievement.va_bank.title": "All-In",
        "achievement.va_bank.desc": "Use all three lifelines on the same question",
        "achievement.own_mind.title": "Own Mind",
        "achievement.own_mind.desc": "Complete the entire game without using any lifelines",
        "achievement.on_the_edge.title": "On the Edge",
        "achievement.on_the_edge.desc": "Give a correct answer with less than 2 seconds left",
        "achievement.bird_in_hand.title": "Bird in Hand",
        "achievement.bird_in_hand.desc": "Take the money on question 12 or higher",
        "achievement.bitter_experience.title": "Bitter Experience",
        "achievement.bitter_experience.desc": "Lose on the final 15th question",
        "achievement.sprinter.title": "Sprinter",
        "achievement.sprinter.desc": "Complete all 15 questions in less than 2 minutes",
        "achievement.intellectual_series.title": "Intellectual Series",
        "achievement.intellectual_series.desc": "Three consecutive games without a single mistake",
        "achievement.magnate.title": "Magnate",
        "achievement.magnate.desc": "Accumulate 1,000,000,000 in total capital",
        "achievement.cautious_strategist.title": "Cautious Strategist",
        "achievement.cautious_strategist.desc": "Take the money 20 times during your career",
        "achievement.history_expert.title": "History Expert",
        "achievement.history_expert.desc": "Give 50 correct answers in the History category",
        "achievement.jack_of_all_trades.title": "Jack of all Trades",
        "achievement.jack_of_all_trades.desc": "Correctly answer questions from 10 different fields",
        "achievement.club_legend.title": "Club Legend",
        "achievement.club_legend.desc": "Collect all 19 other achievements",
    },
}

